# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-12 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiconfig',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='apiconfig',
            old_name='user_id',
            new_name='user',
        ),
    ]
