# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-12 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180212_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfig',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tag', verbose_name='api\u6240\u5c5e\u6807\u7b7e'),
        ),
    ]
