# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-27 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180326_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tag', verbose_name='\u7528\u4f8b\u6807\u7b7e'),
        ),
    ]
