# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-02 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180302_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconf',
            name='name',
            field=models.CharField(default=datetime.datetime(2018, 3, 2, 6, 22, 30, 264733, tzinfo=utc), max_length=50, verbose_name='case\u540d\u79f0'),
            preserve_default=False,
        ),
    ]
