# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180327_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '\u7528\u4f8b', 'verbose_name_plural': '\u7528\u4f8b'},
        ),
        migrations.AddField(
            model_name='result',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='result',
            name='headers',
            field=models.TextField(default='', verbose_name='\u54cd\u5e94\u5934\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='api',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
