# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-29 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180328_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': '\u6d4b\u8bd5', 'verbose_name_plural': '\u6d4b\u8bd5'},
        ),
        migrations.AddField(
            model_name='result',
            name='cookies',
            field=models.TextField(default='', verbose_name='\u54cd\u5e94cookies'),
        ),
        migrations.AddField(
            model_name='result',
            name='request_cookies',
            field=models.TextField(default='', verbose_name='\u8bf7\u6c42cookies'),
        ),
        migrations.AddField(
            model_name='result',
            name='request_headers',
            field=models.TextField(default='', verbose_name='\u8bf7\u6c42\u5934\u4fe1\u606f'),
        ),
    ]
